spring:
  application:
    name: IntelliEdu-api
  session:
    store-type: redis
    timeout: 2592000 # 30 days expiration
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# todo 删掉 redis 后能否运行？
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000