server:
  port: 8083
  servlet:
    context-path: /api/scoring
spring:
  application:
    name: IntelliEdu-scoring-service
  session:
    store-type: redis
    timeout: 2592000 # 30 days expiration
    redis:
      # 禁用 Spring Session 自动配置 Redis 的行为，确保使用云服务商提供的 Redis 配置。
      # 这行配置可以防止 Spring Boot 在启动时尝试对 Redis 进行任何配置更改，从而避免潜在的连接问题或配置冲突
      configure-action: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${INTELLIEDU_SCORING_MYSQL_HOST}
    username: ${INTELLIEDU_SCORING_MYSQL_USERNAME}
    password: ${INTELLIEDU_SCORING_MYSQL_PASSWORD}
  redis:
    database: ${REDIS_DATABASE_NUMBER}
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: 5000
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}
    ssl: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000  # milliseconds
        readTimeout: 10000    # milliseconds